### ISSUE TITLE
Adding bookmarks could fail with older SQLite version

### ISSUE THREAD

**Issue by RealRancor** [owncloud/bookmarks#11]
Hi,

there is a report of an user at the community forums:

https://forum.owncloud.org/viewtopic.php?f=23&t=10514

that adding a bookmark failed with this message:

    {"app":"PHP","message":"SQLSTATE[HY000]: General error: 1 no such function: GROUP_CONCAT at \/var\/www\/html\/***\/owncloud\/lib\/db.php#384","level":4,"time":1366120340}

It seems (according to this changelog: https://www.sqlite.org/releaselog/3_5_4.html) SQlite is official supporting this GROUP_CONCAT function with 3.5.4 at the end of 2007.
I don't think that there are so many systems with that old SQlite versions out there but just want to report it here.

**Comment by blizzz** [comment]
As it's more then 2 years ago, I hope sqlite is more up to date everywhere. Otherwise, please update sqlite ;)
