### ISSUE TITLE
Shouldn’t require protocol like http / https

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/bookmarks#113]
Currently when you put in something like duckduckgo.com or owncloud.org – it won’t work. You need to prepend http:// or https://

That should not be required. It needs to be checked if http / https is present, and if not just prepend that automatically.

cc @ttuxx @gaomi @wakeup

**Comment by TtuxX** [comment]
@jancborchardt pull request merged, issue solved

**Comment by jancborchardt** [comment]
@TtuxX awesome, thank you again! :)

**Comment by TtuxX** [comment]
@jancborchardt You are welcome ! Let me know if I can help on similar tasks.

**Comment by jancborchardt** [comment]
@TtuxX cool! If you want to take a stab at fixing the navigation, take a look at https://github.com/owncloud/bookmarks/issues/118 :)

(And are you already in our #owncloud-dev IRC channel?)
