### ISSUE TITLE
Cannot add bookmark through the bookmarklet for pages with slashe(s) in tittle.

### ISSUE THREAD

**Issue by Scorry** [owncloud/bookmarks#115]
Click on bookmarklet in this case do nothing. But can do it successfully from the main window of ownCloud.

**Comment by Chouchen** [comment]
I don't have this issue.
I can had [this link](https://www.inslash.com/) via the bookmarklet.

Are you sure it's not linked to #103 ?

**Comment by Scorry** [comment]
Yes. Excuse me.
