### ISSUE TITLE
Can't add tags to bookmarks, fixed db-prefix "oc" is used

### ISSUE THREAD

**Issue by tflidd** [owncloud/bookmarks#121]
I added a new bookmark (perfect). Then, I tried to attach some tags, I can create some tags and click on the "save"-button. Unfortunately nothing is saved.

In the owncloud logfiles, I find this entry:

````
{"reqId":"54abc8e97ac59","app":"index","message":"Exception: Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO `bookmarks_tags` (`bookmark_id`, `tag`) select ?, ? from dual where not exists(select * from oc_bookmarks_tags where bookmark_id = ? and tag = ?)':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_bookmarks_tags' doesn't exist - Caused by: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_bookmarks_tags' doesn't exist[42S02] ","level":4,"time":"January 06, 2015 11:37:13","method":"POST","url":"\/owncloud\/index.php\/apps\/bookmarks\/ajax\/editBookmark.php"}
````
My database-name is "cloud" and I don't use a table-prefix:
config/config.php:
````
 'dbtableprefix' => '',
````
So of course the table oc_bookmarks_tags doesn't exist, but bookmarks_tags does. It seems to me as if you had added a fixed table-prefix "oc" somewhere.

It's a owncloud 7.0.4 installation on Linux with mysql-database. The error has to be very recent, as I was able to add tags not so long ago (in October 2014).

**Comment by tflidd** [comment]
I found the corresponding line:
https://github.com/owncloud/bookmarks/blob/master/controller/lib/bookmarks.php#L494

I removed the oc-prefix and no it works for me.

**Comment by LukasReschke** [comment]
That's a bug then.

**Comment by tflidd** [comment]
Closed: https://github.com/owncloud/bookmarks/pull/129
