### ISSUE TITLE
Why the news unread number are not shown on the icon?

### ISSUE THREAD

**Issue by thenamelessthing** [owncloud/bookmarks#122]
At home the news icon show how many unread articles I have but at work it display an "?". The url are the same on both pc...

https://sc-cdn.scaleengine.net/i/37311fccfe7ccb7f139e94e47f9afc73.png
![image](https://cloud.githubusercontent.com/assets/10235448/5783607/7b2f9522-9d92-11e4-819e-aeb8ddece367.png)

**Comment by Chouchen** [comment]
Are you sure this issue is related to bookmark app ?

**Comment by blizzz** [comment]
Unrelated to bookmarks.
