### ISSUE TITLE
Not all tags shown

### ISSUE THREAD

**Issue by mase76** [owncloud/bookmarks#123]
Hi!
On my machine, not all used bookmark tags are shown in the overview.
When I type a not shown tag into the filter, the bookmarks of this tag are
shown. I use OC 7.0.4 with the shipped bookmark app.

**Comment by TtuxX** [comment]
Hello @mase76 !

Have you tried removing the shipped bookmark app and getting the OC bookmarks app directly from github ? :)
Could you tell me whether it works or still not after doing so ?

**Comment by mase76** [comment]
Yes, I tried 7.0.4 from github. Same behaviour. 8.x does not work with my OC
version 7.0.4.

**Comment by Chouchen** [comment]
FYI, I can't reproduce this bug on OC 8.0.2

**Comment by mase76** [comment]
Sorry, forgot to report. This issue isn't any more with recent versions.

Am 20. März 2015 01:18:18 MEZ, schrieb Shikiryu <notifications@github.com>:
>FYI, I can't reproduce this bug on OC 8.0.2
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/bookmarks/issues/123#issuecomment-83818693

-- 
gpg: 383107c4
https://www.setho.org/people
