### ISSUE TITLE
Adding tags is missing in new bookmarklet 

### ISSUE THREAD

**Issue by jeka** [owncloud/bookmarks#127]
I can't add tags to bookmarks anymore with the new bookmarklet. That is a big issue especially for me as usually I am adding tons of bookmarks on daily basis and I am used to assign "priority" tags on them for later reference. 

Generally the new bookmark window (via bookmarklet) is quite not user friendly. 
2 input lines + text area....
Ok in the text area there is a placeholder "Description of the page" but input lines are prefiled and which line is what its not so clear on brief look.

And ... not tags assignment :-/

**Comment by buzzra** [comment]
I am seeing this problem also. Tags can be added from the web interface, AFTER the bookmark is created. Also affects the 3rd party Chrome extension.

**Comment by mbressman** [comment]
Further info - the old bookmarklet from v7.x didn't work at all after upgrading to v8.0 - removing it and adding the one from the v8.0 bookmarks page (under the settings in the lower left corner) allows adding bookmarks, but as mentioned, the tags option is missing which is especially important in keeping all bookmarks organized.

**Comment by utahbmxer** [comment]
Seeing this also, noticed the day that ownCloud 8 was released.

**Comment by raimerik** [comment]
There is hardly ANYTHING which works with the new OC8-Bookmarklet!

1) Title gets changed: "Nokia X1-01 vs. Archos 50 Diamond - GSMArena.com" >>> "Compare phones - GSMArena.com"
2) LINK GETS CUT OFF: http://www.gsmarena.com/compare.php3?idPhone1=3962&idPhone2=7042 >>> http://www.gsmarena.com/compare.php3?idPhone1=3962

The ONLY thing working is the DESCRIPTION...

Utterly useless! Is this a BETA release? Anyone checking functionality before releasing core functions?

BTW: I'm running a new OC8 setup - not an upgrade.

Cheers, raimerik

**Comment by LukasReschke** [comment]
Well, ownCloud's core functionality is file sync and share. Apps like Bookmarks are community contributed ;-)

**Comment by LukasReschke** [comment]
=> As long as nobody cares to fixes this, this will stay this way.

**Comment by raimerik** [comment]
Hi Lukas!

I did not want to come across as the know-it-all-complainer - I'm just an end user, happy having mastered on OwnCloud installation on my shared hosting. I'm not a programmer.

But I'm a bit surprised to so a major stable release (OC7 > OC8) with this lack of beta testing or foresight...

Cheers, raimerik

**Comment by LukasReschke** [comment]
https://owncloud.org/faq/#upgradeyet

And again: Nobody here earns money with the bookmarks app and nobody really maintains it. So if you want this fixed some dev needs to step up and want to fix this ;-)

**Comment by rakekniven** [comment]
People are not forced to upgrade to v8
There are many apps around which are not ready for v8. Core apps are ready.
Please consider to create a bounty for wanted issue.

**Comment by buzzra** [comment]
If this app is a community app with no support and known to be briken, then why is it a recommended app? If Owncloud devs are not going to support an app, then it needs to be taken off the recommended apps list. If I install an app that is RECOMMENDED by Owncloud, then I expect it to be maintained. 
I understand the community supported nature of these things and I realize that I am using the community version at no cost. I am grateful for all the work the devs do and I want tht project to succeed wildly. But sometimes it seems Owncloud wants to talk about all the things the server can do, when in reality they don't support most of them. I think it does a disservice to users and damages the reputation of the project.I don't wantto see this happen. 

Thanks for a great project,

buzz

**Comment by tflidd** [comment]
Can you test the pull request from @Chouchen applied: https://github.com/owncloud/bookmarks/pull/132 ?

**Comment by jonmach** [comment]
Still broken: I made the changes kindly submitted by Chouchen but it still doesn't work unfortunately.
Ah well...

**Comment by Chouchen** [comment]
*doesn't work* does not help debugging :/
It works for me and another person so it should work for everyone :-)

**Comment by jonmach** [comment]
I agree that a simple "Doesn't work", doesn't help.  I did provide additional log data.
Did you redownload the app from owncloud.com (https://apps.owncloud.com/content/download.php?content=168710&id=1&tan=21849937) or did you simply use the default content that came with the auto update?

I'm not being pedantic here, I'm just trying to get to the same point as you.  I have made your changes and they conform to all the line numbers that were in my source but they don't seem to address the problem with main.php.  

I will try again with a freshly downloaded bookmark app

**Comment by jonmach** [comment]
OK - one step forward.  I've now downloaded the master directly from github.  Disabled and reenabled the app.  There are now tags when I add a new page using the 'Add to ownCloud' Firefox button.
However, there is still an issue with an undefined index based on req_tag.  Therefore, when I show the bookmarks app, I don't get an option to filter on any existing tags.
Any idea why I might be seeing this?

**Comment by Chouchen** [comment]
Alright, my PR is not merged with the main project right now ; it needs to be reviewed and tested first. 
Those modifications are viewable [here](https://github.com/owncloud/bookmarks/pull/132/files) and downloadable (**for test only !**) [here](https://github.com/Chouchen/bookmarks)

I made another PR ( #135 ) for that error ( which is already defined in #126 )  
Since it's not merged either, it's not present in the main project too.

**Comment by tflidd** [comment]
@LukasReschke Now, some users have submitted pull request: https://github.com/owncloud/bookmarks/issues/127#issuecomment-80394218
Some users have tested them and https://github.com/owncloud/bookmarks/pull/132 seems to work. Can someone from the developer team review the code and merge it?

**Comment by shaneonabike** [comment]
:+1:  It works for me perfectly thanks so much for your work. I also agree that it's totally worth the merge :)

**Comment by dnaber-de** [comment]
Same problem here. I updated a owncloud install from 6.0.1 to 6.08, to 7.0.6. and finally to 8.0.4 using `occ`. After reactivating the Bookmark app and updating the bookmarklet I cannot add tags to new bookmarks any longer. 

Also, there are errors in the admin log: 

```
Error 	PHP 	Undefined index: req_tag at /var/www/owncloud/apps/bookmarks/templates/main.php#40 	2015-07-03T14:21:04+00:00
Error 	PHP 	Undefined index: req_tag at /var/www/owncloud/apps/bookmarks/templates/main.php#44 	2015-07-03T14:20:36+00:00
```

Any chance to see that pull request in a official release?

**Comment by tflidd** [comment]
@dnaber-de Please don't mix different issues. Your other error has been reported here: https://github.com/owncloud/bookmarks/issues/142

**Comment by Chouchen** [comment]
or #126
