### ISSUE TITLE
Confirmation of bookmark saved

### ISSUE THREAD

**Issue by jonmach** [owncloud/bookmarks#136]
Hi,

Previously, simply hitting 'Save' was enough to save the bookmark.  Now in 8.0(.2), you get a:

"Bookmark added. You can close the window now."

That's all well and good, but it forces you to then have to close the window.  Why is this necessary?  Save should have been enough.  It's nice to have this as a debugging/confirmation trace but it should be assumed.  If there was a problem then sure, show a message that "Bookmark was NOT added: <more info here>".

I've tried to dig into the code to understand how I can avoid showing this but it's not entirely clear.  PHP is not my primary coding medium.

Any advice on where I should look greatly appreciated (and/or) and option to select/deselect this in BM preferences.

**Comment by blizzz** [comment]
@jancborchardt do you remember or are you aware that the not-closing was implemented from an UX PoV? To me it does not see much useful either.

**Comment by jonmach** [comment]
I wasn't aware of this, but it seems like a constant irritation that could be resolved with a simple preferences option.

**Comment by blizzz** [comment]
My gut feeling is to simply restore the old behaviour if there is no real need to keep it open… otherwise yes, config option, though i  prefer to avoid it.

**Comment by jonmach** [comment]
I agree with you, but it seems there must have been enough desire to include it at some point.  A preference would keep everyone happy. I don't personally know what code to remove or I would do it for my own installation.

**Comment by blizzz** [comment]
I might look into in within one week, or not, depends on time and priorities.

**Comment by jancborchardt** [comment]
@jonmach with ownCloud we prefer to solve things properly instead of adding more and more preferences.

@blizzz as far as I know there was no UX decision taken to change this to what it is now. It also seems strange to me, and I agree moving back to the original behavior could be better. There should be some quick feedback (like shwoing a checkmark for 1 or 2 seconds) but then it should close.

**Comment by jonmach** [comment]
@jan - adding preferences are not my personal style, but it keeps what I thought were previous well thought out decisions. Saying that it's not doing it 'properly' is a little emotive/religious and doesn't really help.

**Comment by blizzz** [comment]
> Saying that it's not doing it 'properly' is a little emotive/religious and doesn't really help.

On the surface, but it has technical impacts. More configurations means more codepaths, means more possibilities for bugs, makes it harder to maintain and test. Being spare with configurations increases quality and thus UX. It does not mean that there should not be anything to configure, only switches that are reasonable. Saving a bookmark is nothing that takes ages, quickly after saving you will get the confirmation. If successful, there is no reason (that I can imagine) not to close automatically after a bit.

**Comment by jonmach** [comment]
I agree with you.  More code-paths mean more complication, less efficiency etc and are all good reasons not to create preferences.

**Comment by jancborchardt** [comment]
@jonmach what @blizzz said and also, it’s offloading decisions to users that we should do correctly in the software. Sorry I was not being precise enough.

Introducing preferences is a common problem in open source software which does not lead to a better product. As Havoc Pennington already said in 2002:
> Reading dozens of GNOME and Red Hat bugs per day, I find that users ask for a preference by default.

I can recommend reading the full article [Free Software UI](http://ometer.com/free-software-ui.html).

**Comment by blizzz** [comment]
Fixed with https://github.com/owncloud/bookmarks/pull/179
