### ISSUE TITLE
Pages with long title can not be saved

### ISSUE THREAD

**Issue by Scorry** [owncloud/bookmarks#138]
Trying to enter address directly in owncloud interface also does not help: it seems parser tries to extract title before saving bookmark and generates exception.
Length of <title> tag does not strictly limited by the standards, so may be corresponding table in database may be enlarged to, say, 512 symbols? And cutted by script after that enormous size?..

**Comment by TtuxX** [comment]
Hello @Scorry :)
Your issue seems to be a duplicate of https://github.com/owncloud/bookmarks/issues/29
Could you check this and close this issue if so ? Thanks

**Comment by Scorry** [comment]
Hello TtuxX :)
Yep. Closed as duplicated.
