### ISSUE TITLE
Failure to add bookmark for certain pages fails silently

### ISSUE THREAD

**Issue by LordVan** [owncloud/bookmarks#139]
I just tried to add some bookmarks, but it seems like it doesn't like some urls and fails silently:

http://www.animania.de/animagic/animagic-2015-musicacts/musikacts-airi.html

on the admin page i found this in the log then:

		Exception: {"Message":"An exception occurred while executing '\n\t\t\tINSERT INTO \"oc_bookmarks\"\n\t\t\t(\"url\", \"title\", \"user_id\", \"public\", \"added\", \"lastmodified\", \"description\")\n\t\t\tVALUES (?, ?, ?, ?, cast(extract(epoch from current_timestamp) as integer), cast(extract(epoch from current_timestamp) as integer), ?)\n\t\t\t' with params [\"http:\\\/\\\/www.animania.de\\\/animagic\\\/animagic-2015-musicacts\\\/musikacts-airi.html\", \"AiRI :: AnimagiC :: Convention, Cosplay, Showacts, Manga-Stars. AnimagiC das Mekka von Anime-, Manga- und J-Culture-begeisterten Besuchern.<\\\/title><link rel=\\\"shortcut icon\\\" href=\\\"favicon.ico\\\" type=\\\"image\\\/x-icon\\\" \\\/><link rel=\\\"shortcut icon=\\\"href=\\\"fileadmin\\\/templates\\\/img\\\/favicon.ico\\\" type=\\\"image\\\/x-icon\\\" \\\/><link rel=\\\"icon\\\" href=\\\"fileadmin\\\/templates\\\/img\\\/favicon_ani.gif\\\" type=\\\"image\\\/gif\\\" \\\/><link href='http:\\\/\\\/fonts.googleapis.com\\\/css?family=Open+Sans:400,400italic,700,700italic,800' rel='stylesheet' type='text\\\/css'><link href='http:\\\/\\\/fonts.googleapis.com\\\/css?family=Montserrat+Alternates:400,700' rel='stylesheet' type='text\\\/css'>\\n\\t<title>AiRI\", \"lordvan\", 0, \"\"]:\n\nSQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(140)","Code":0,"Trace":"#0 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), '\\n\\t\\t\\tINSERT INTO...', Array)\n#2 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/lib\/private\/db\/statementwrapper.php(63): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/apps\/bookmarks\/controller\/lib\/bookmarks.php(469): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/apps\/bookmarks\/controller\/rest\/bookmarkcontroller.php(84): OCA\\Bookmarks\\Controller\\Lib\\Bookmarks::addBookmark('lordvan', Object(OC\\AppFramework\\Db\\Db), 'http:\/\/www.anim...', 'AiRI :: Animagi...', Array, '', false)\n#5 [internal function]: OCA\\Bookmarks\\Controller\\Rest\\BookmarkController->newBookmark('http:\/\/www.anim...', Array, '0', '', false, '')\n#6 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#7 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Bookmarks\\Controller\\Rest\\BookmarkController), 'newBookmark')\n#8 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Bookmarks\\Controller\\Rest\\BookmarkController), 'newBookmark')\n#9 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('BookmarkControl...', 'newBookmark', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/bookmarks...')\n#13 \/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/index.php(36): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/secure.lordvan.com\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractPostgreSQLDriver.php","Line":91}

**Comment by LordVan** [comment]
seems to be related to - or duplicate of - bug #29

**Comment by Scorry** [comment]
Yes. I can save this page with modified postgres table. Please close this issue as duplicated.

**Comment by LordVan** [comment]
I patched bookmarks.php instead. see my comment on bug #29
