### ISSUE TITLE
Adding some bookmarks results in 500 error in log

### ISSUE THREAD

**Issue by ege1** [owncloud/bookmarks#149]
For some sites I can't add bookmarks using bookmarks app. Clicking on save shows the waiting icon and stays unchanged afterwards. The same happens if I try to add a bookmark directly with the "add" button on the bookmarks page.

Maybe it is related to the title of the site I want to bookmark, but even changing that doesn't fix the issue.

Example site is: http://www.metasploitation.com/

Logfile shows: - -  17/May/2015:11:01:45 +0200 "POST /index.php" 500

Kind Regards,

Erik

**Comment by ege1** [comment]
Sorry, forgot to say: Version of owncloud is 8,0,3,4

bookmark itself:
<ocsid>166042</ocsid>
        <version>0.4</version>

**Comment by TtuxX** [comment]
Hello @ege1 :)
I can personally not reproduce your bug adding the very same website on OC 8.0.3 with bookmarks 0.4 ...
- On which DB back-end and OS is your ownCloud instance currently running ?
- Is this behavior specific to http://www.metasploitation.com/ or also happens adding other websites ?
- Did this started happening after a specific event you remember of (OC update, News app update...) ?

Thanks :)

**Comment by ege1** [comment]
Hello @TtuxX, 

The database back-end was the right hint:

May 19 16:40:44 neo postgres[11310]: [3-1] ERROR:  value too long for type character varying(140)
May 19 16:40:44 neo postgres[11310]: [3-1] ERROR:  value too long for type character varying(140)
May 19 16:40:44 neo postgres[11310]: [3-2] STATEMENT:  UPDATE "oc_bookmarks" SET "lastmodified" = cast(extract(epoch from current_timestamp) as integer)  , title = $1  WHERE "url" = $2 and "user_id" = $3
May 19 16:40:44 neo postgres[11310]: [3-2] STATEMENT:  UPDATE "oc_bookmarks" SET "lastmodified" = cast(extract(epoch from current_timestamp) as integer)  , title = $1  WHERE "url" = $2 and "user_id" = $3

I just don't get where these more than 140 characters should be as I tried shortening the title, already. And the title has 99 characters...

But to answer your questions:

- owncloud is running on a debian wheezy installation, but is installed using the latest tarball.
- database back-end is on a different machine and is postgreSQL.
- most websites are working, but some don't.
- No event, it just didn't work for some sites.

I'll try to get the values for the above updates

Cheers,

Erik

**Comment by ege1** [comment]
OK, it's the title. Does it get the title directly from the site, even if I edit it before saving?

It looks like there is some overhead, maybe due to escaping to hit that 140 chars limit.

Unfortunately postgreSQL doesn't log the content of prepared statements if they lead to an error :(

Do you need anything else from me?

**Comment by TtuxX** [comment]
No, thank you @ege1, your description is enough for me to see once again the origin of this issue. Your bug is related to issue https://github.com/owncloud/bookmarks/issues/29
Can you close this issue and participate to the issue #29 discussion instead, as yours is a duplicate ? 
This is not the first time we hear about this and I think it is time to expand the char limit to at least 256 and trim any other characters as this unfortunate problem has been unfixed for quite a long time and regurlarly keeps being reported.. ^^

**Comment by ege1** [comment]
Thanks
