### ISSUE TITLE
Filtering by tag doesn't show any bookmark

### ISSUE THREAD

**Issue by claudex** [owncloud/bookmarks#15]
When I click on a tag, it doesn't show the bookmarks tagged with it.

Exemple before clicking on a tag:
![bug_bookmark1](https://f.cloud.github.com/assets/396774/463560/5a1ded9c-b578-11e2-8bca-97bde996d6ac.png)

After:
![bug_bookmark2](https://f.cloud.github.com/assets/396774/463561/5e13513a-b578-11e2-9ea6-aef715bf0281.png)

**Comment by blizzz** [comment]
Close as fixed, please reopen in case you should still experience it.
