### ISSUE TITLE
CSP "default-src 'none';" prevents importing of bookmarks in version 0.4 in oC 8.1.0

### ISSUE THREAD

**Issue by shtrom** [owncloud/bookmarks#180]
When loading the Bookmarks app, an error shows up in the developer tools/Firebug:

    Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://HOST 'unsafe-eval'").
    onsubmit attribute on DIV element

This seems to prevent uploading HTML bookmarks files using the import tool.

Looking into the base oC code, in `lib/public/appframework/http/contentsecuritypolicy.php`, in function `buildPolicy()`, the default CSP is set to `default-src 'none';`, and get updated based on various parameters.
 
Replacing the `'none'` with `'self'` fixes the issue, and I could upload my bookmarks.

A more sustainable way would be to use the functions from the oC ContentSecurityPolicy object, probably `addAllowedScriptDomain()`, to add `self`.

**Comment by blizzz** [comment]
IIRC this can be overriden/configured by the app (no, @LukasReschke ?), you mention a way yourself. Would you mind trying to get this implemented and open a PR? If there is no other way around.

**Comment by LukasReschke** [comment]
`'self'` is already whitelisted in the script src. `default-src` is something different.

The actual error in Chrome (which usually better when it comes to debugging issues like that) is:

> Refused to frame 'http://localhost/master/index.php/apps/bookmarks/bookmark/import' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

So we just need to allow iframes. => https://github.com/owncloud/bookmarks/pull/182

**Comment by LukasReschke** [comment]
Note: I do wonder why iframes are used for that. That seems pretty unusual.

**Comment by entyrion** [comment]
I am having similar issues uploading HTML bookmark files. (Firefox reports "import error," and Chrome reports import successful, but the bookmarks are not actually uploaded). I'll check if the workaround from @shtrom above works.

Dumb question: will the actual resolution to the bug need to be implemented in oC itself, or can the fix be made in the next version of the app?

**Comment by blizzz** [comment]
@entyrion better test whether the proposed fix from @LukasReschke works :) 
https://github.com/owncloud/bookmarks/pull/182

**Comment by entyrion** [comment]
@blizzz I'd be happy to, though I confess I'm a noob.... @shtrom's method sounded pretty quick and easy; navigate to the .php file in oC, then modify the parameter inside the buildPolicy() function there. Even a hobbyist/dude off the street like me can try that out :)

At the risk of sounding stupid, I don't see any similarly clear instructions as to exactly what the fix is at #182, just a small bit of code, and "sweet, I'll check it out this weekend." I'm afraid I'm not sure what to do, though I'd be willing to try. Is that an update to a particular .php config file (webviewcontroller.php)? If so, where is it located within oC and I can try to replace the existing file with that one and see if it works.

**Comment by ezraholm50** [comment]
Indeed could anyone get us a bit more detailed guide on how to? Can't seem to find the files you guys are talking about.

Kind regards

**Comment by entyrion** [comment]
Hi all, 

From my testing, I can confirm that #182 does in fact work for me. To @ezraholm50 and others, I basically:

1. navigated to my ownCloud installation's app folder, and then to the 'controller' folder within the boomkarks directory: <YMMV depending on your installation>/owncloud/apps/bookmarks/controller

2. opened <YMMV depending on your installation>/owncloud/apps/bookmarks/controller/webviewcontroller.php with a text editor.

3. added the green lines and subtracted the red line in the code from #182.

4. saved changes, restarted oC server, used the bookmarks app's import tool from the web UI.

5. import successful; seems to stick after subsequent server reboot!
