### ISSUE TITLE
Importing doenst work oc 8.1

### ISSUE THREAD

**Issue by ezraholm50** [owncloud/bookmarks#184]
Hey,

First off great app! Though if i import from html -> chrome it says the're imported but nothing shows up?
Please help me!

Kind regards,

Ez

**Comment by entyrion** [comment]
I can confirm that I am also unable to import bookmark files. In Firefox I receive an "import error" message. When I tried in Chrome, the same thing happened: Chrome says the import is complete, but the bookmarks don't actually show up.

**Comment by ezraholm50** [comment]
Tried it also in firefox, same thing. Also exact same error on chrome!

**Comment by entyrion** [comment]
Hi @ezraholm50, I noticed #180, I think that may be addressing the underlying issue.

**Comment by ezraholm50** [comment]
Hey Entyrion, 

Thanks alot 2 more issues alike, though can't seem to work around the problem like you said. We'll wait for them to reply, if i get across anything that solves it i'll let you know. Thanks again!

Kind regards

**Comment by entyrion** [comment]
Hi @ezraholm50, per my comments in #180 and #182, that fix seems to work for me!

**Comment by zirydy** [comment]
@entyrion 
Thanks! The newest build fixed the issue for me.
