### ISSUE TITLE
[Feature Request] Add tags fields to bookmarklet

### ISSUE THREAD

**Issue by TaniaDow** [owncloud/bookmarks#188]
It would be nice to immediately add tags when saving a bookmark via the bookmarklet. Currently, you have to save the bookmark, then go into Owncloud to add the tags.

Thanks.

**Comment by tflidd** [comment]
This was reported some time ago but should be fixed with this pull request: https://github.com/owncloud/bookmarks/pull/173
This pull request is probably not part of the latest version on the app store. Either apply this patch manually or try a more recent version from github.

**Comment by TaniaDow** [comment]
Thanks!
