### ISSUE TITLE
Update version in the app-Store

### ISSUE THREAD

**Issue by tflidd** [owncloud/bookmarks#192]
@blizzz, @eMerzh There were some ugly bugs that have already been fixed in github (with backports). But on a new installation or upgrade, the broken version from the app-store is loaded (last update Feb 9: https://apps.owncloud.com/content/show.php/Bookmarks?content=168710).
Users continue to report fixed bugs because of this: https://github.com/owncloud/bookmarks/issues/188

**Comment by tflidd** [comment]
For other users, you can download the latest stable8-branch from github and move it manually into /path/to/owncloud/apps/bookmarks (if there already is a bookmarks-folder, delete it first):
https://github.com/owncloud/bookmarks/archive/stable8.zip

**Comment by blizzz** [comment]
I made release in the app store for all branches to all owncloud versions since 8.0.

I hope nothing break :dancers:

**Comment by blizzz** [comment]
Of course, download 8.1 and 8.2 version via app management does not work, because of missing extension (as it is possible to host only one file on apps.owncloud.com and others need to be linked, which i did from my OC via public sharing–…) https://github.com/owncloud/core/pull/20196 has the fix.
