### ISSUE TITLE
Increase version for 9.0

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/bookmarks#197]
Just a warning, when stable8.2 is branched off in core (most likely today), the info.xml needs to be adjusted to allow installing against 9.0
```xml
	<dependencies>
		<owncloud min-version="8.1" max-version="8.2" />
	</dependencies>
```
Also the requiremin section should be removed in favor of the other section:
```xml
<requiremin>8</requiremin>
```

At the end the app version should also be increased.

**Comment by blizzz** [comment]
Thanks for the heads up, fix in https://github.com/owncloud/bookmarks/pull/205
