### ISSUE TITLE
[8.1.3] Error in log file by adding ad new bookmark

### ISSUE THREAD

**Issue by cdamken** [owncloud/bookmarks#200]
Every time I add a bookmark I see an error in the log file.

The bookmark is added and works without problem, but why shows always an error?

Server Architecture:

•    Operating system (name and version number):
Ubuntu 14.04.3 LTS \n \l

•    Webserver (name and version number):
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 24 2015 17:25:11
 
•    Apache modules enabled as declared in:
access_compat.load
alias.conf
alias.load
auth_basic.load
authn_core.load
authn_file.load
authz_core.load
authz_host.load
authz_user.load
autoindex.conf
autoindex.load
deflate.conf
deflate.load
dir.conf
dir.load
env.load
filter.load
mime.conf
mime.load
mpm_prefork.conf
mpm_prefork.load
negotiation.conf
negotiation.load
php5.conf
php5.load
rewrite.load
setenvif.conf
setenvif.load
socache_shmcb.load
ssl.conf
ssl.load
status.conf
status.load
 
•    Database (name and version number):
mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Connection id:          180125
Current database:
Current user:           root@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         5.5.44-MariaDB-1ubuntu0.14.04.1 (Ubuntu)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 19 days 22 hours 1 min 31 sec
Threads: 4  Questions: 13363814  Slow queries: 0  Opens: 187  Flush tables: 2  Open tables: 98  Queries per second avg: 7.765

•    PHP (version number):
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
 with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

•   PHP cache manager
Package: php5-apcu
Status: install ok installed
Version: 4.0.6-1
 
•    ownCloud Enterprise Server Version

{"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":""}

•    Tell us your migration path of the ownCloud software
8.1.0.8 -> 8.1.3.0

•    Do you have records from your migration steps?
No
  
•    List of owncloud-apps enabled/ in use (see bold printed apps in: administration → Apps):
Enabled:
 - activity: 2.0.2
 - bookmarks: 0.4
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - delete_confirmation: 1.0.1
 - direct_menu: 0.3
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking:
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - galleryplus: 14.1.0
 - ownnote: 1.05
 - provisioning_api: 0.2
 - registration: 0.0.7
 - sharelinks: 1.0.1
 - tasks: 0.8
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - documents
 - encryption
 - external
 - files_videoviewer
 - gallery
 - logreader 1.0.1 <-Activated to the Admins
 - user_external
 - user_ldap
 - user_webdavauth

•    The content of your config/config.php:
<?php
$CONFIG = array (
  'instanceid' => 'xxxxx',
  'passwordsalt' => 'xxxxxj',
  'secret' => 'xxxxx',
  'trusted_domains' =>
  array (
    0 => 'cloud.damken.com',
  ),
  'datadirectory' => '/mnt/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'xxxxx',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxx',
  'loglevel' => 0,
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 10485760,
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'cloud',
  'mail_domain' => 'damken.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'xxxxx',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'xxxxx',
  'mail_smtppassword' => 'xxxxx',
  'theme' => 'damken',
  'maintenance' => false,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'appstore.experimental.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);

•    Storage type and setup
NFS

•    LDAP
None

•    Loadbalancer
None

•    High availability setup
None

•    Proxies
None

•    Customizations
None

•    Additional architectural features (disaster recovery setup, etc.):
None

•   Log file:
```
{"reqId":"e5oHNdb+C1oRBxXZr7MO","remoteAddr":"84.170.205.145","app":"PHP","message":"Undefined index: req_tag at \/var\/www\/html\/owncloud\/apps\/bookmarks\/templates\/main.php#40","level":3,"time":"2015-10-19T10:38:03+02:00","method":"GET","url":"\/index.php\/apps\/bookmarks\/"}
{"reqId":"e5oHNdb+C1oRBxXZr7MO","remoteAddr":"84.170.205.145","app":"PHP","message":"Undefined index: req_tag at \/var\/www\/html\/owncloud\/apps\/bookmarks\/templates\/main.php#44","level":3,"time":"2015-10-19T10:38:03+02:00","method":"GET","url":"\/index.php\/apps\/bookmarks\/"}
{"reqId":"fzc+6yTIXmZwtuRUtOfZ","remoteAddr":"84.170.205.145","app":"PHP","message":"Undefined index: req_tag at \/var\/www\/html\/owncloud\/apps\/bookmarks\/templates\/main.php#40","level":3,"time":"2015-10-19T10:46:59+02:00","method":"GET","url":"\/index.php\/apps\/bookmarks\/"}
{"reqId":"fzc+6yTIXmZwtuRUtOfZ","remoteAddr":"84.170.205.145","app":"PHP","message":"Undefined index: req_tag at \/var\/www\/html\/owncloud\/apps\/bookmarks\/templates\/main.php#44","level":3,"time":"2015-10-19T10:46:59+02:00","method":"GET","url":"\/index.php\/apps\/bookmarks\/"}

```

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by tflidd** [comment]
There is a new version on the App Store where this issue is fixed: https://github.com/owncloud/bookmarks/issues/196#issuecomment-143679227

**Comment by blizzz** [comment]
ty @tflidd
