### ISSUE TITLE
Update from 0.4 to 0.5 fails with "Failed to open archive when installing app"

### ISSUE THREAD

**Issue by RealRancor** [owncloud/bookmarks#202]
### Steps to reproduce
1. Have bookmarks 0.4 installed
2. Click on button to update to bookmarks 0.5

### Expected behaviour
Update from 0.4 to 0.5 should be done without an issue

### Actual behaviour
Update failed with message "Failed to open archive when installing app"
(Other app updates like calendar and contacts where done successfully on the same installation)

### Server configuration
**Operating system**: Debian Jessie

**PHP version:** 5.6.14

**ownCloud version:** 8.1.3

#### Web server error log
```
Nothing relevant
```

#### ownCloud log (data/owncloud.log)
```
Nothing relevant
```

**Comment by tflidd** [comment]
Ref: https://github.com/owncloud/bookmarks/issues/192#issuecomment-152680430

**Comment by RealRancor** [comment]
Ah, nice. Thanks for the reference. Will keep this open until https://github.com/owncloud/core/pull/20196 is fixed.

**Comment by marcosms** [comment]
Same problem here. I have a spanish translation of owncloud. When i try to update this app, i can see the message "Falló la apertura ded fichero mientras se instalaba la aplicación" (the same message of the first post, but translated to spanish). Is there any workaround to this issue?

Thanks.

**Comment by RealRancor** [comment]
@marcosms 
> Is there any workaround to this issue?

Install the app manually until the fix in core https://github.com/owncloud/core/pull/20196 is released in one of the next oC versions.

**Comment by MorrisJobke** [comment]
This will be fixed in core 8.1.5, 8.2.1 and 9.0.0
