### ISSUE TITLE
Update from 0.4 to 0.6 fails with "Failed to open archive when installing app" 

### ISSUE THREAD

**Issue by hitam4450** [owncloud/bookmarks#203]
OC 8.2, DEBIAN Jewssie 8.2 Update from 0.4 ---> 0.6

See enclosed screenshot!

![oc_bookmark](https://cloud.githubusercontent.com/assets/9738727/10863028/4e1a90d0-7fc0-11e5-89aa-fc07cc1142c2.png)
Regards, hitam4450

**Comment by tflidd** [comment]
Duplicate: https://github.com/owncloud/bookmarks/issues/202
