### ISSUE TITLE
longer bookmarknames

### ISSUE THREAD

**Issue by RobTranquillo** [owncloud/bookmarks#21]
Although the webpage is wide enough, bookmarks will be cut off, so it is no not charming to use them. The matter can be fixed simply by a little hands on css i think.

a picture for better understanding

![image](https://f.cloud.github.com/assets/311739/641550/c2332004-d338-11e2-8f34-7081cefed5b4.png)

**Comment by blizzz** [comment]
Please reopen if it is still valid.
