### ISSUE TITLE
Error trying to update bookamrks app

### ISSUE THREAD

**Issue by hitam4450** [owncloud/bookmarks#214]
Using OC 8.2 I tried to update my current installation of the bookmarks app to version 0.6.

I received the following error message; (see enclosed screen shot)
![bookmarksoc82](https://cloud.githubusercontent.com/assets/9738727/11125917/cb53d542-896c-11e5-86f5-b0f303c5b932.png)
What happened ?
regards, hitam4450

**Comment by tflidd** [comment]
You need to wait for the release of OC 8.2.1:
https://github.com/owncloud/core/pull/20196

Duplicate of https://github.com/owncloud/bookmarks/issues/203 which is already duplicate of https://github.com/owncloud/bookmarks/issues/202
