### ISSUE TITLE
Adding bookmarks without dialogue

### ISSUE THREAD

**Issue by timorei** [owncloud/bookmarks#221]
Hi,

I really like the feature to replace any third-party "remember this for later" kind of bookmark (like the mozilla pocket integration). But there are just too many clicks required. (yes, I am THAT spoiled).

Would a "add to ownCloud" button be possible that just adds the current page as a bookmark, with no more questions or popups showing? 

That would make this a lot more pleasant to use (for me, and people like that).

**Comment by webmarka** [comment]
Agree with you @timorei, there's *at least* one extra click that could be removed as a first step in reducing the time it takes to bookmark a page : the last click to close the window. 

Maybe this could be an option in admin or personal settings that says : "Close window after successfully added bookmark".

**Comment by selivan** [comment]
:+1: Option "Close window after successfully added bookmark"

**Comment by blizzz** [comment]
That's already implemented, just needs to be released :)
