### ISSUE TITLE
Call to undefined method OC_L10N::get() in /var/www/owncloud/apps/bookmarks/appinfo/app.php on line 31 under ownCloud 9

### ISSUE THREAD

**Issue by strugee** [owncloud/bookmarks#229]
I've just upgraded to ownCloud 9.0 and I'm getting the following error in my Apache logs:

    [Wed Mar 09 11:50:55.004798 2016] [:error] [pid 11562] [client 50.205.125.154:51320] PHP Fatal error:  Call to undefined method OC_L10N::get() in /var/www/owncloud/apps/bookmarks/appinfo/app.php on line 31

Disabling the bookmarks app fixes this.

(I'm in a hurry so I'm skipping the template, but I'd be happy to fill it out later if necessary.)

**Comment by StopTrain** [comment]
I can confirm this issue as well.  There was a 'fix' in the comments on the owncloud apps site, however, that didn't get the app working properly for me :)

**Comment by tflidd** [comment]
What php-version are you using? I can run it without error (php 5.6.17 on debian 8)

**Comment by StopTrain** [comment]
Well, I ended up blowing away what was there, and with owncloud 9, just installed the app from the Apps section.  Got it back up and running.

**Comment by strugee** [comment]
@tflidd 

```
% php -v
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

Some more information: I'm on Bookmarks 0.6, ownCloud is installed from the OBS repo, and I'm on MySQL. I've upgraded this ownCloud several times (never skipped a version) and app integrity checking is enabled and passing. I'm not using anything fancy, like encryption or external user backends or anything.

**Comment by tflidd** [comment]
@strugee Are you sure you have the current version. Just delete the apps/bookmarks-folder from your installation and install the bookmarks-app again. It should download the code itself.

**Comment by strugee** [comment]
@tflidd tried that. Now I can't find the app anywhere in the Apps page.

**Comment by tflidd** [comment]
Perhaps it wasn't properly tagged in the app-store. You can download it from apps.owncloud.com or here from github and unpack it into /path/to/owncloud/apps/bookmarks

**Comment by blizzz** [comment]
> [Wed Mar 09 11:50:55.004798 2016] [:error] [pid 11562] [client 50.205.125.154:51320] PHP Fatal error:  Call to undefined method OC_L10N::get() in /var/www/owncloud/apps/bookmarks/appinfo/app.php on line 31

Fixed with 46599d82241bbe9eb11bfeb39f517f73eb65d0e8 but it is not released yet indeed

**Comment by strugee** [comment]
@blizzz since this is a fairly serious compatibility problem, any chance we could get a release sooner rather than later?

**Comment by blizzz** [comment]
I'd love to do it these days but depends on the time i find. Chances are not too bad I can get something done this weekend.

**Comment by strugee** [comment]
Wonderful, thanks.

**Comment by blizzz** [comment]
Just published :tada:
