### ISSUE TITLE
Bookmarks Chrome Extension: Internal Server Error

### ISSUE THREAD

**Issue by feluxe** [owncloud/bookmarks#231]
In order to get access to my OwnCloud Bookmarks with Chrome/Chromium I installed the "OwnCloud Bookmarks" extension.

Within the options menu of the extension I enter my OwnCloud URL like so:
https://myserver.com/owncloud

Now, if I click on the extension icon it displays "Internal Server Error" and nothing else happens...

Does anyone know how to solve this?
Or does anyone know how to browse and search my OwnCloud Bookmarks with Chrome/Chromium?

Thanks!

**Comment by blizzz** [comment]
Cannot say whether this is related to the extension or the bookmarks app. Can you provide more details (e.g. versions, log) as in this [template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md)? Thx!

**Comment by milesgillham** [comment]
Server side. I have the same issue with OC 9.0.1 on vanilla LAMP (CentOS 7, Apache, MariaDB, PHP 5.65).

`Class 'OCA\Bookmarks\Controller\Rest\OCA\Bookmarks\Controller\Lib\Helper' not found at /var/www/html/owncloud/apps/bookmarks/controller/rest/bookmarkcontroller.php#266`

Someone in the forum had same problem with 8.2.2 but same issue from the look of it:

["Internal Server Error" with bookmarks addons](https://forum.owncloud.org/viewtopic.php?t=32872)

I can confirm that applying the same change of adding a slash in front of OCA appears to fix the problem. That is, in owncloud/apps/bookmarks/controller/rest/bookmarkcontroller.php change line 266 from:

`OCA\Bookmarks\Controller\Rest\OCA\Bookmarks\Controller\Lib\Helper`

to

 `\OCA\Bookmarks\Controller\Rest\OCA\Bookmarks\Controller\Lib\Helper`

But haven't done any further analysis.

Cheers, Miles

**Comment by blizzz** [comment]
The issue was fixed with by #146 but is missing backports, yet. I will take care of it.

**Comment by blizzz** [comment]
Backports in #268 #269 and #270 merged, will be shipped with next release
