### ISSUE TITLE
500 for POST for a new bookmark

### ISSUE THREAD

**Issue by theScrabi** [owncloud/bookmarks#282]
### Steps to reproduce
1. add a new bookmark (does not matter how)

### Expected behaviour
A new bookmark should appere in the list

### Actual behaviour
Nothing happens

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache/2.4.18

**Database:** mysql 5.7

**PHP version:** 7.0.8

**ownCloud version:** 9.1

**Bookmarks version:** v0.5.2

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
suse package source

**Comment by theScrabi** [comment]
This is the error i get:
`
{"reqId":"4Im\/y1dkuKKjXhqLRxuh","remoteAddr":"188.194.240.199","app":"index","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ClientException\",\"Message\":\"Client error response [url] https:\\\/\\\/fachschaft.in.th-nuernberg.de\\\/forum\\\/aktuell [status code] 403 [reason phrase] Forbidden\",\"Code\":403,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(32): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(109): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(136): GuzzleHttp\\\\Client->get('https:\\\/\\\/fachsch...', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/bookmarks\\\/controller\\\/lib\\\/bookmarks.php(572): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/fachsch...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/bookmarks\\\/controller\\\/rest\\\/bookmarkcontroller.php(100): OCA\\\\Bookmarks\\\\Controller\\\\Lib\\\\Bookmarks::getURLMetadata('https:\\\/\\\/fachsch...')\\n#13 [internal function]: OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController->newBookmark('https:\\\/\\\/fachsch...', Array, 0, 'Fachschaft IN: ...', false, '')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController), 'newBookmark')\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController), 'newBookmark')\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('BookmarkControl...', 'newBookmark', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/bookmarks...')\\n#21 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}","level":3,"time":"2016-08-19T20:10:48+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/bookmarks\/bookmark","user":"the-scrabi"}
`

**Comment by blizzz** [comment]
Works for me. 

What the problem seems to be that the requested page returns a 403, Forbidden. I agree, we should not fail here.

**Comment by blizzz** [comment]
@theScrabi could you check whether  https://github.com/owncloud/bookmarks/pull/284 solves it?

**Comment by blizzz** [comment]
closing as fixed by https://github.com/owncloud/bookmarks/pull/285
