### ISSUE TITLE
500 Internal Server Error when app is opened without user logged in

### ISSUE THREAD

**Issue by eppfel** [owncloud/bookmarks#289]
### Steps to reproduce
1. Logout out of Nextcloud, if you are logged in
2. Go directly to `https://[your nextcloud url]/apps/bokmarks/`

### Expected behaviour
The page should redirect to `/login?redirect_url=[nextcloud-path]/apps/bookmarks`

### Actual behaviour
500 – Internal Server Error
Log: `Call to a member function getUID() on null at /var/www/virtual/eppcloud/html/apps/bookmarks/appinfo/application.php#41`

I'm pretty sure this is not related to my configuration, because I could reproduce the error with/without prettyURLs on two separate installations.

---

### Server configuration
**Operating system**: Cent OS 6
**Web server:** Apache 2.4
**Database:** MySQL
**PHP version:** 5.6
**ownCloud version:** Nextcloud 10.0 / Nextcloud 11.0 alpha (git)
**Bookmarks version:** 0.9.0
**Updated from an older ownCloud or fresh install:** updated from Nextcloud 9.0.53 / git fresh install

```
No errors have been found.
```

**The content of config/config.php:**
```
{
        "instanceid": "ocztm7fxpnfx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "exmple.org"
        ],
        "datadirectory": "\/home\/eppcloud\/ocdata",
        "overwrite.cli.url": "https:\/\/example.org",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "eppcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/home\/eppcloud\/.redis\/sock",
            "port": 0,
            "timeout": 0
        },
        "forcessl": true,
        "mail_from_address": "botler",
        "mail_smtpmode": "php",
        "mail_domain": "example.org",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "beta",
        "debug": true
    }
```
```
{
        "instanceid": "ocdbr1r0xj5l",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dev.example.org"
        ],
        "datadirectory": "\/var\/www\/virtual\/eppfel\/dev.example.org\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/dev.example.org\/nextcloud",
        "dbtype": "mysql",
        "version": "9.2.0.0",
        "dbname": "eppfel",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
```

**Are you using external storage:** No

**Are you using encryption:** No

**Are you using an external user-backend:** No

### Client configuration
**Browser:** Chrome 52
**Operating system:** Mac 10.11

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Xz9tCNL0G1eQobJoVYB2","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Call to a member function getUID() on null at \/var\/www\/virtual\/eppfel\/dev.example.org\/nextcloud\/apps\/bookmarks\/appinfo\/application.php#41","level":3,"time":"2016-09-05T12:40:19+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/bookmarks\/","user":"--"}
```

**Comment by e-alfred** [comment]
Can confirm this bug on Owncloud 9.1.0 as well.

**Comment by blizzz** [comment]
Thanks for reporting! PR with fix https://github.com/owncloud/bookmarks/pull/290

**Comment by e-alfred** [comment]
Do you intent to release a version with the bugfix included?

**Comment by blizzz** [comment]
At some point, yes, but I do not think this is critical. I'd collect some other fixes or improvements for a release.
