### ISSUE TITLE
ownCloud bookmark app for android now open source

### ISSUE THREAD

**Issue by theScrabi** [owncloud/bookmarks#293]
Just wanted to announce that the ownCloud bookmark app for [android](https://play.google.com/store/apps/details?id=cz.nethar.owncloudbookmarks) is now open source, and available on [github](https://github.com/Nethar/owncloud-bookmarks).

**Comment by DeastinY** [comment]
:heart:

**Comment by theScrabi** [comment]
I want to put it on [f-droid](https://f-droid.org/) but before we can do that we'd have to reflector it a bit. It's not working anymore... at least it's not working for me. The app still works as a crawler. Don't you guys have some REST api to connect to the owncloud app?

**Comment by blizzz** [comment]
@theScrabi thanks for the info, really appreciate it! However, the better place to announce this are [Nextcloud](https://help.nextcloud.com) /owncloud Forums (and a blog if you got one). Thus I need to close this, at it's neither a bug or a request.

> The app still works as a crawler. Don't you guys have some REST api to connect to the owncloud app?

Yes, that's an open issue unfortunately (see e.g. https://github.com/owncloud/bookmarks/pull/218).

**Comment by theScrabi** [comment]
@blizzz Sorry don't like Nextcloud.
