### ISSUE TITLE
More than 10 tags and all bookmarks disappear.

### ISSUE THREAD

**Issue by lyallp** [owncloud/bookmarks#39]
Imported my Firefox bookmarks by exporting to html and importing into OC 5.0.10 Bookmarks (downloaded GIT version of Bookmark app as at 28-Aug-2013)
Looked fine initially.
Started editing tags.
1. A bookmark of the name 'XRAY' simply refused to allow addition of a tag
2. Once I had more than 10 tags, all bookmarks disappear, unless I filter by a bookmark
3. It's a pain in the arse if you import lots of bookmarks and you want to tag them. There appears to be no obvious way to filter by bookmarks with NO tags, otherwise, you have to constantly scroll down after every tag update. With many bookmarks, the scrolling gets tedious.

Otherwise, another step towards me ditching delicious.com in favour of my own hosted bookmarks :)

**Comment by Chouchen** [comment]
I can't reproduce on OC8
