### ISSUE TITLE
Publish at http://apps.owncloud.com/

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/bookmarks#49]
Go go go @eMerzh http://apps.owncloud.com/

**Comment by Chouchen** [comment]
Is it done? I see 2 "bookmarks app" which seems to be from owncloud team : 
https://apps.owncloud.com/content/show.php/Bookmarks+8.0?content=168710
https://apps.owncloud.com/content/show.php/Bookmarks?content=166042

1 should be deleted and if the other is this current project, delete this issue.

**Comment by blizzz** [comment]
It's the same app, but OC 7 and OC 8 versions. So it is published (and thus i close). I will take care of having them up to date.
