### ISSUE TITLE
Saving bookmark fails w/o error if no description given

### ISSUE THREAD

**Issue by enkore** [owncloud/bookmarks#51]
When creating (or saving an existing) bookmark the process fails without any indication of failure if no description is given.

Recommendation: make description optional.

**Comment by Chouchen** [comment]
I almost never add a description to my bookmarks and it never fails for that reason.
I guess this issue is not up to date and should be closed.

**Comment by TtuxX** [comment]
@Chouchen You're right, I think this issue has been fixed
