### ISSUE TITLE
Bookmark problem with german "Umlaute" OC6RC1

### ISSUE THREAD

**Issue by Hausmarke** [owncloud/bookmarks#61]
When i try to add a bookmark with Umlaute in it OC it destroys the link.

The following link
http://wiki.piratenpartei.de/HowTo_Emails_verschlüsseln_mit_PGP_mit_Thunderbird

will be:
http://wiki.piratenpartei.de/HowTo_Emails_verschl%25C3%25BCsseln_mit_PGP_mit_Thunderbird

Tried with actual FF and IE under Win7.

running OC on:
Ubuntu Linux 12.04.2,Apache version 2.4.6 , MySQL version 5.5.32

**Comment by blizzz** [comment]
Close as fixed.
