### ISSUE TITLE
Add bookmark button wont make any bookmarks

### ISSUE THREAD

**Issue by redherring36** [owncloud/bookmarks#63]
I have seen a lot of problems with the bookmarks app while searching for a solution but  Icant seem to find the problem I'm having. I am running owncloud 6 stable with mysql 5.6, windows 7, and php5.3 and I got it up and running fine but later I tried to go into bookmarks and add a bookmark but it wont do anything, I input an address click add and nothing happens. I have checked the logs and nothing is appearing and no error warnings generated so I don't know what is going wrong. Someone please help

**Comment by Chouchen** [comment]
Is it still relevant?

**Comment by blizzz** [comment]
Closed for inactivity.
