### ISSUE TITLE
Import button not working in IE Version: 11.0.9600.16521

### ISSUE THREAD

**Issue by ocontant** [owncloud/bookmarks#70]
IE Version: 11.0.9600.16521

https://drive.yopcloud.com/index.php/apps/bookmarks#

click on gear and Import button

Cannot open file explorer when we click on Import. The button doesn't do anything.

**Comment by Chouchen** [comment]
It works for me on my instance with IE 11.0.9600.17691
Your instance needs login/password so I can't check. Plus, it has certificate issue (it may comes from here)

**Comment by blizzz** [comment]
Could not be reproduced and no one else chimed in → close.
