### ISSUE TITLE
"Automatic logon rejected" error when using bookmarklet

### ISSUE THREAD

**Issue by giovi321** [owncloud/bookmarks#73]
everytime I try to use the Bookmarklet on ownCloud 6.0, if I'm not logged in already, I get the following error: "Automatic logon rejected", and I can't even login from the popup window that opens. I have to login and then I can use the bookmarklet.
Attacched a screenshot of the error (found on google, but it's the same as mine).
![oc](https://cloud.githubusercontent.com/assets/6443515/3355106/6cf67156-faae-11e3-9837-80630aa4b5d8.png)

**Comment by blizzz** [comment]
Nothing to do from bookmarks PoV, also apparently only affects OC 6.
