### ISSUE TITLE
integrate Firefox sync app

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/bookmarks#8]
As discussed on the mailing list, the Bookmarks app and the Firefox bookmark sync app should be combined. The bookmarks in Firefox and in the Bookmarks app should be one and the same, synced.

**Comment by blizzz** [comment]
Basically dead as mozilla_sync is stalled due to Mozilla more or less killing the protocol and ability to add own sync server. I close it for now. When Mozilla starts to support it again, we can reopen this or open a new issue. But right now there's nothing we can do.
