### ISSUE TITLE
Unusable in browser

### ISSUE THREAD

**Issue by mase76** [owncloud/bookmarks#94]
Hi!
There is an oc bookmarks app for android and an extension for chrome / chromium. But there
is nothing for firefox. So I have to use it in the browser. But this is unusable. The bookmarks are
not sorted, and when clicking a tag, the list gets empty.

**Comment by blizzz** [comment]
maybe you did have an old / not up to date version? If it's in git, it should been shipped earlier or later. Since the file you picked from hand fixed it, i close it as fixed.
